set out_script_ptr [open $::env(SYNTH_STOP_MODULE_SCRIPT) w]
puts $out_script_ptr "hierarchy -check -top $::env(DESIGN_NAME)"
puts $out_script_ptr "select -module {\\rv64_l2_fsm}"
puts $out_script_ptr "setattr -mod -set keep_hierarchy 1"
puts $out_script_ptr "select -clear"
puts $out_script_ptr "select -module {\$paramod\$432c118da4c62ce34d13236ca06889b22143a251\\rv64_l2_grant_update_engine}"
puts $out_script_ptr "setattr -mod -set keep_hierarchy 1"
puts $out_script_ptr "select -clear"
puts $out_script_ptr "select -module {\$paramod\$9c14bdfbb5d39f6ee2ae95179d2dd54af5523683\\rv64_l2_dir_lookup}"
puts $out_script_ptr "setattr -mod -set keep_hierarchy 1"
puts $out_script_ptr "select -clear"
puts $out_script_ptr "select -module {\$paramod\$9c14bdfbb5d39f6ee2ae95179d2dd54af5523683\\rv64_l2_probe_planner}"
puts $out_script_ptr "setattr -mod -set keep_hierarchy 1"
puts $out_script_ptr "select -clear"
puts $out_script_ptr "select -module {\$paramod\$f88c73f2a693c493b1d09a1e09f52486a80be55a\\rv64_l2_probe_engine}"
puts $out_script_ptr "setattr -mod -set keep_hierarchy 1"
puts $out_script_ptr "select -clear"
puts $out_script_ptr "select -module {\\rv64_l2_plru}"
puts $out_script_ptr "setattr -mod -set keep_hierarchy 1"
puts $out_script_ptr "select -clear"
close $out_script_ptr
